# Spring Boot Application and Actuator configuration
server:
  port: 18115

management:
  endpoints:
    web:
      exposure:
        include: "health,info,loggers"


# ----------------------------------------------------------------------------------------------------------------------
# Database configurations
# ----------------------------------------------------------------------------------------------------------------------
spring:
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://ec2-18-235-45-217.compute-1.amazonaws.com:5432/d1a2gmh5ru2ht5
    username: ddmzkaytlsdxdm
    password: 65984a5474bf5eb749e9d1be7d2a359c950a68bb7496f8e4be912816f2795f9e
    configuration:
      connectionInitSql: SELECT 1
      maximumPoolSize: 4
      minimumIdle: 2
      connectionTimeout: 10000
      idleTimeout: 20000
      maxLifetime: 60000
      validationTimeout: 3000
      leakDetectionThreshold: 1000


## Logging level configuration
logging:
  level:
    root: info
    org.springframework.web.client: debug
    org.apache.http: info
    com.payu: debug

# Circuit breaker configuration
resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
  instances:
    superBankPayment:
      baseConfig: default
      failureRateThreshold: 30
      slowCallRateThreshold: 50
      slowCallDurationThreshold: 40000
      permittedNumberOfCallsInHalfOpenState: 10
      slidingWindowType: TIME_BASED
      slidingWindowSize: 60
      minimumNumberOfCalls: 10
      waitDurationInOpenState: 15s

# Retry Configuration
resilence4J.retry:
  instances:
    retryPayment:
      maxRetryAttempts: 2
      waitDuration: 100

feign:
  client:
    config:
      superbank-api:
        url: http://localhost:9124/superbank-api
        connectTimeout: 3000
        readTimeout: 5000
        loggerLevel: basic
      fraudmax-api:
        url: http://localhost:9124/fraudmax-api
        connectTimeout: 3000
        readTimeout: 5000
        loggerLevel: basic